name: Build using dotnet

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: dotnet publish .\ESchoolBot\ESchoolBot.csproj --output .\app\

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: app
